/* tslint:disable */
/* eslint-disable */
/**
 * 学工大系统API
 * 学工大系统 Issues Documentation
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ForecastDto } from '../models';
import { JsonResultForecastConciseVo } from '../models';
import { JsonResultSchoolAndOfferDetailsVo } from '../models';
/**
 * PythonAIApi - axios parameter creator
 * @export
 */
export const PythonAIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 进行预测，需传递预测模型所需参数
         * @param {ForecastDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        doForecast: async (body: ForecastDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling doForecast.');
            }
            const localVarPath = `/oversea/forecast/do_forecast`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 传递学校id，获取包含学校详细信息、offer及相应学生信息
         * @param {number} schoolId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        query6: async (schoolId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            if (schoolId === null || schoolId === undefined) {
                throw new RequiredError('schoolId','Required parameter schoolId was null or undefined when calling query6.');
            }
            const localVarPath = `/oversea/forecast/query`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (schoolId !== undefined) {
                localVarQueryParameter['schoolId'] = schoolId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PythonAIApi - functional programming interface
 * @export
 */
export const PythonAIApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 进行预测，需传递预测模型所需参数
         * @param {ForecastDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async doForecast(body: ForecastDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<JsonResultForecastConciseVo>>> {
            const localVarAxiosArgs = await PythonAIApiAxiosParamCreator(configuration).doForecast(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 传递学校id，获取包含学校详细信息、offer及相应学生信息
         * @param {number} schoolId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async query6(schoolId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<JsonResultSchoolAndOfferDetailsVo>>> {
            const localVarAxiosArgs = await PythonAIApiAxiosParamCreator(configuration).query6(schoolId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * PythonAIApi - factory interface
 * @export
 */
export const PythonAIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 进行预测，需传递预测模型所需参数
         * @param {ForecastDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async doForecast(body: ForecastDto, options?: AxiosRequestConfig): Promise<AxiosResponse<JsonResultForecastConciseVo>> {
            return PythonAIApiFp(configuration).doForecast(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 传递学校id，获取包含学校详细信息、offer及相应学生信息
         * @param {number} schoolId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async query6(schoolId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<JsonResultSchoolAndOfferDetailsVo>> {
            return PythonAIApiFp(configuration).query6(schoolId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PythonAIApi - object-oriented interface
 * @export
 * @class PythonAIApi
 * @extends {BaseAPI}
 */
export class PythonAIApi extends BaseAPI {
    /**
     * 进行预测，需传递预测模型所需参数
     * @param {ForecastDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PythonAIApi
     */
    public async doForecast(body: ForecastDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<JsonResultForecastConciseVo>> {
        return PythonAIApiFp(this.configuration).doForecast(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 传递学校id，获取包含学校详细信息、offer及相应学生信息
     * @param {number} schoolId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PythonAIApi
     */
    public async query6(schoolId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<JsonResultSchoolAndOfferDetailsVo>> {
        return PythonAIApiFp(this.configuration).query6(schoolId, options).then((request) => request(this.axios, this.basePath));
    }
}
