/* tslint:disable */
/* eslint-disable */
/**
 * 学工大系统API
 * 学工大系统 Issues Documentation
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SchoolInfoConciseVo } from './school-info-concise-vo';
/**
 * 
 * @export
 * @interface ForecastConciseVo
 */
export interface ForecastConciseVo {
    /**
     * 推荐学校信息
     * @type {Array<SchoolInfoConciseVo>}
     * @memberof ForecastConciseVo
     */
    school?: Array<SchoolInfoConciseVo>;
}
