/* tslint:disable */
/* eslint-disable */
/**
 * 学工大系统API
 * 学工大系统 Issues Documentation
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ForecastDto
 */
export interface ForecastDto {
    /**
     * 地区
     * @type {string}
     * @memberof ForecastDto
     */
    location?: string;
    /**
     * 前六学期成绩
     * @type {number}
     * @memberof ForecastDto
     */
    score?: number;
    /**
     * 雅思成绩
     * @type {number}
     * @memberof ForecastDto
     */
    ielts?: number;
    /**
     * 托福成绩
     * @type {number}
     * @memberof ForecastDto
     */
    toefl?: number;
    /**
     * GRE成绩
     * @type {number}
     * @memberof ForecastDto
     */
    gre?: number;
}
