/* tslint:disable */
/* eslint-disable */
/**
 * 学工大系统API
 * 学工大系统 Issues Documentation
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * offer加学生信息
 * @export
 * @interface OfferWithStuInfoVo
 */
export interface OfferWithStuInfoVo {
    /**
     * 对应学校id，便于对应
     * @type {number}
     * @memberof OfferWithStuInfoVo
     */
    schoolId?: number;
    /**
     * offer的专业
     * @type {string}
     * @memberof OfferWithStuInfoVo
     */
    offerMajor?: string;
    /**
     * 在北邮的专业
     * @type {string}
     * @memberof OfferWithStuInfoVo
     */
    major?: string;
    /**
     * 前六学期成绩
     * @type {number}
     * @memberof OfferWithStuInfoVo
     */
    score?: number;
    /**
     * 前六学期排名
     * @type {number}
     * @memberof OfferWithStuInfoVo
     */
    ranking?: number;
    /**
     * 雅思成绩
     * @type {number}
     * @memberof OfferWithStuInfoVo
     */
    ielts?: number;
    /**
     * 托福成绩
     * @type {number}
     * @memberof OfferWithStuInfoVo
     */
    toefl?: number;
    /**
     * GRE成绩
     * @type {number}
     * @memberof OfferWithStuInfoVo
     */
    gre?: number;
}
