/* tslint:disable */
/* eslint-disable */
/**
 * 学工大系统API
 * 学工大系统 Issues Documentation
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OfferInfo
 */
export interface OfferInfo {
    /**
     * id
     * @type {number}
     * @memberof OfferInfo
     */
    id?: number;
    /**
     * 用户id
     * @type {number}
     * @memberof OfferInfo
     */
    uid?: number;
    /**
     * offer
     * @type {string}
     * @memberof OfferInfo
     */
    offer?: string;
    /**
     * 专业
     * @type {string}
     * @memberof OfferInfo
     */
    major?: string;
}
