/* tslint:disable */
/* eslint-disable */
/**
 * 学工大系统API
 * 学工大系统 Issues Documentation
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OverseaStuInfo
 */
export interface OverseaStuInfo {
    /**
     * id
     * @type {number}
     * @memberof OverseaStuInfo
     */
    id?: number;
    /**
     * 学工号
     * @type {number}
     * @memberof OverseaStuInfo
     */
    uid?: number;
    /**
     * 专业
     * @type {string}
     * @memberof OverseaStuInfo
     */
    major?: string;
    /**
     * 生源地
     * @type {string}
     * @memberof OverseaStuInfo
     */
    hometown?: string;
    /**
     * 高考成绩
     * @type {number}
     * @memberof OverseaStuInfo
     */
    entranceScore?: number;
    /**
     * 前六学期成绩
     * @type {number}
     * @memberof OverseaStuInfo
     */
    score?: number;
    /**
     * 前六学期排名
     * @type {number}
     * @memberof OverseaStuInfo
     */
    ranking?: number;
    /**
     * 去向大学
     * @type {string}
     * @memberof OverseaStuInfo
     */
    university?: string;
    /**
     * 雅思成绩
     * @type {number}
     * @memberof OverseaStuInfo
     */
    ielts?: number;
    /**
     * 托福成绩
     * @type {number}
     * @memberof OverseaStuInfo
     */
    toefl?: number;
    /**
     * GRE成绩
     * @type {number}
     * @memberof OverseaStuInfo
     */
    gre?: number;
}
