/* tslint:disable */
/* eslint-disable */
/**
 * 学工大系统API
 * 学工大系统 Issues Documentation
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SchoolPastRankingDto
 */
export interface SchoolPastRankingDto {
    /**
     * 
     * @type {string}
     * @memberof SchoolPastRankingDto
     */
    schoolName?: string;
    /**
     * 
     * @type {number}
     * @memberof SchoolPastRankingDto
     */
    schoolId?: number;
    /**
     * 
     * @type {number}
     * @memberof SchoolPastRankingDto
     */
    year?: number;
    /**
     * 
     * @type {number}
     * @memberof SchoolPastRankingDto
     */
    rank?: number;
}
