/* tslint:disable */
/* eslint-disable */
/**
 * 学工大系统API
 * 学工大系统 Issues Documentation
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 推荐学校信息
 * @export
 * @interface SchoolInfoConciseVo
 */
export interface SchoolInfoConciseVo {
    /**
     * 学校id
     * @type {number}
     * @memberof SchoolInfoConciseVo
     */
    id?: number;
    /**
     * 学校名称
     * @type {string}
     * @memberof SchoolInfoConciseVo
     */
    name?: string;
    /**
     * 学校QS排名
     * @type {string}
     * @memberof SchoolInfoConciseVo
     */
    ranking?: string;
    /**
     * 推荐指数
     * @type {number}
     * @memberof SchoolInfoConciseVo
     */
    recommendation?: number;
    /**
     * 校徽图标
     * @type {string}
     * @memberof SchoolInfoConciseVo
     */
    icon?: string;
    /**
     * 位置（国家）
     * @type {string}
     * @memberof SchoolInfoConciseVo
     */
    location?: string;
}
