/* tslint:disable */
/* eslint-disable */
/**
 * 学工大系统API
 * 学工大系统 Issues Documentation
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OfferWithStuInfoVo } from './offer-with-stu-info-vo';
import { SchoolInfoDetailsVo } from './school-info-details-vo';
/**
 * 
 * @export
 * @interface SchoolAndOfferDetailsVo
 */
export interface SchoolAndOfferDetailsVo {
    /**
     * 
     * @type {SchoolInfoDetailsVo}
     * @memberof SchoolAndOfferDetailsVo
     */
    schoolInfoDetailsVo?: SchoolInfoDetailsVo;
    /**
     * offer加学生信息
     * @type {Array<OfferWithStuInfoVo>}
     * @memberof SchoolAndOfferDetailsVo
     */
    offerWithStuInfo?: Array<OfferWithStuInfoVo>;
}
