/* tslint:disable */
/* eslint-disable */
/**
 * 学工大系统API
 * 学工大系统 Issues Documentation
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SchoolInfo
 */
export interface SchoolInfo {
    /**
     * id
     * @type {number}
     * @memberof SchoolInfo
     */
    id?: number;
    /**
     * 学校名称
     * @type {string}
     * @memberof SchoolInfo
     */
    name?: string;
    /**
     * 排名
     * @type {string}
     * @memberof SchoolInfo
     */
    ranking?: string;
    /**
     * 校徽url
     * @type {string}
     * @memberof SchoolInfo
     */
    icon?: string;
    /**
     * 所在国家
     * @type {string}
     * @memberof SchoolInfo
     */
    location?: string;
    /**
     * 简介
     * @type {string}
     * @memberof SchoolInfo
     */
    introduction?: string;
}
