/* tslint:disable */
/* eslint-disable */
/**
 * 学工大系统API
 * 学工大系统 Issues Documentation
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SchoolPastRankingVo } from './school-past-ranking-vo';
/**
 * 学校详细信息
 * @export
 * @interface SchoolInfoDetailsVo
 */
export interface SchoolInfoDetailsVo {
    /**
     * id
     * @type {number}
     * @memberof SchoolInfoDetailsVo
     */
    id?: number;
    /**
     * 学校名称
     * @type {string}
     * @memberof SchoolInfoDetailsVo
     */
    name?: string;
    /**
     * 排名
     * @type {string}
     * @memberof SchoolInfoDetailsVo
     */
    ranking?: string;
    /**
     * 校徽url
     * @type {string}
     * @memberof SchoolInfoDetailsVo
     */
    icon?: string;
    /**
     * 所在国家
     * @type {string}
     * @memberof SchoolInfoDetailsVo
     */
    location?: string;
    /**
     * 简介
     * @type {string}
     * @memberof SchoolInfoDetailsVo
     */
    introduction?: string;
    /**
     * 学校往年排名
     * @type {Array<SchoolPastRankingVo>}
     * @memberof SchoolInfoDetailsVo
     */
    schoolPastRankingVos?: Array<SchoolPastRankingVo>;
}
