/* tslint:disable */
/* eslint-disable */
/**
 * 学工大系统API
 * 学工大系统 Issues Documentation
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GrantedAuthority } from './granted-authority';
import { Role } from './role';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 用户id
     * @type {number}
     * @memberof User
     */
    id?: number;
    /**
     * 用户名，创建时需要
     * @type {string}
     * @memberof User
     */
    username?: string;
    /**
     * 密码，创建时需要
     * @type {string}
     * @memberof User
     */
    password?: string;
    /**
     * 账户余额，创建时无需
     * @type {number}
     * @memberof User
     */
    account?: number;
    /**
     * 昵称
     * @type {string}
     * @memberof User
     */
    nickName?: string;
    /**
     * 头像地址，创建时无需
     * @type {string}
     * @memberof User
     */
    avatar?: string;
    /**
     * 性别
     * @type {string}
     * @memberof User
     */
    sex?: string;
    /**
     * 用户组别，创建时无需
     * @type {string}
     * @memberof User
     */
    userGroup?: string;
    /**
     * 
     * @type {Array<Role>}
     * @memberof User
     */
    roles?: Array<Role>;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    enabled?: boolean;
    /**
     * 
     * @type {Array<GrantedAuthority>}
     * @memberof User
     */
    authorities?: Array<GrantedAuthority>;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    accountNonLocked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    credentialsNonExpired?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    accountNonExpired?: boolean;
}
