/* tslint:disable */
/* eslint-disable */
/**
 * 学工大系统API
 * 学工大系统 Issues Documentation
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Role } from './role';
/**
 * 
 * @export
 * @interface UserVo
 */
export interface UserVo {
    /**
     * 用户id
     * @type {number}
     * @memberof UserVo
     */
    id?: number;
    /**
     * 用户名，创建时需要
     * @type {string}
     * @memberof UserVo
     */
    username?: string;
    /**
     * 昵称
     * @type {string}
     * @memberof UserVo
     */
    nickName?: string;
    /**
     * 头像地址，创建时无需
     * @type {string}
     * @memberof UserVo
     */
    avatar?: string;
    /**
     * 性别
     * @type {string}
     * @memberof UserVo
     */
    sex?: string;
    /**
     * 用户组别，创建时无需
     * @type {string}
     * @memberof UserVo
     */
    userGroup?: string;
    /**
     * 用户角色
     * @type {Array<Role>}
     * @memberof UserVo
     */
    roles?: Array<Role>;
}
